name: sweet-warning

on: 
  push:
    branches:
      - main
      - master
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: 16.15.1
          registry-url: https://npm.pkg.github.com/
          scope: '@RaphaelBRodrigues'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
