name: "publish on npm"

on: 
  push:
    branches:
      - main
      
jobs:
  publish-on-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setting node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Setting npm registry
        run:  npm config set registry http://registry.npmjs.org
&& echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
      - name: Publishing package on NPM
        run: npm publish --userconfig=~/.npmrc --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}